### ISSUE TITLE
Remove dependency on machinectl

### ISSUE THREAD

**Issue by metmajer** [jptomo/ansible-connection-nsenter#2]
Hi @jptomo! I tried to execute your example in README.md, but keep failing with the following error when executing the playbook on Mac OS X:

```
GATHERING FACTS *************************************************************** 
fatal: [apache] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 960, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/Library/Python/2.7/site-packages/ansible/runner/connection.py", line 35, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/Library/Python/2.7/site-packages/ansible/utils/plugins.py", line 219, in get
    return getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
  File "/Users/cwat-metmajer/Workspace/Ansible-Docker/connection_plugins/nsenter.py", line 34, in __init__
    if not bool(self._extract_var('Name')):
  File "/Users/cwat-metmajer/Workspace/Ansible-Docker/connection_plugins/nsenter.py", line 58, in _extract_var
    output = subprocess.check_output(['machinectl', 'show', self.host])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Obviously, I my Mac lacks the `machinectl` command which is used in `self._extract_var` to find a value for a particular name. Would it be possible to replace this with an appropriate `docker` command? Any idea? Thanks! Great Work!

**Comment by metmajer** [comment]
@jptomo, I just noticed that Docker will soon ship with a docker.py connection plugin that leverages `docker exec`: https://github.com/ansible/ansible/pull/11650. That's exactly what I need.
